name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.3', '3.4', '4.0' ]
        actionpack: [ '7.2', '8.0', '8.1', 'edge' ]

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/actionpack_${{ matrix.actionpack }}.gemfile
      BUNDLE_WITH: test
    steps:
      - uses: actions/checkout@v3

      - name: Install Brotli development headers
        run: sudo apt-get update && sudo apt-get install -y libbrotli-dev

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake test
        timeout-minutes: 3
